### ISSUE TITLE
Add Group Layer support to `arc_open()`

### ISSUE THREAD

**Issue by elipousson** [R-ArcGIS/arcgislayers#120]
**Is your feature request related to a problem? Please describe.**

`arc_open()` returns a `NULL` value when supplied with a Group Layer URL instead of returning a valid object or returning an error. `fetch_layer_metadata()` already works with Group Layer URLs so it shouldn't take too many changes to get this working. I expect this issue is also somewhat related to #57.

Here is a reprex showing the issue:

``` r
library(arcgislayers)
library(arcgisutils)

url <- "https://geodata.baltimorecity.gov/egis/rest/services/CitiMap/DOT_Layers/MapServer/0"

layer <- arc_open(url)

str(layer)
#>  NULL

layer_meta <- fetch_layer_metadata(httr2::request(url), token = NULL)

str(layer_meta$type)
#>  chr "Group Layer"
```

<sup>Created on 2023-12-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Describe the solution you'd like**

`arc_open()` should just work with Group Layers without a hiccup. `arc_select()` should support selection of a layer from within the group. If the `get_layer()` helper function is required, this workflow should be documented within `arc_select()`. `arc_read()` (if it is added as planned) should support the selection of a layer from a group by name similar to the `sheet` parameter in `googlesheets4::read_sheet()` or `openxlsx2::read_xlsx()`.

**Additional context**

For context, based on [the URL handling code from `{esri2sf}`](https://github.com/elipousson/esri2sf/blob/13ec67cc2b7d929106aafd57db422307e0651d64/R/esriUrl.R), there are 6 main types of services (this may not be comprehensive):

- "MapServer",
- "FeatureServer",
- "GPServer",
- "GeocodeServer",
- "GeometryServer",
- "ImageServer"

Feature Layers and Group Layers are two of twelve different layer types documented in [this page on ArcGIS Pro](https://pro.arcgis.com/en/pro-app/latest/help/mapping/layer-properties/feature-layers.htm) (unsure if they all have web service equivalents or not). 

I'd like to see Group Layers supported added in a way that provides a template for layer handling across the full range of layer types in the future.

**Comment by JosiahParry** [comment]
Good catch! We can add the known classes that you've described. But I am sure there are more! They don't match up identically with Pro either 🙃
