### ISSUE TITLE
gateway timeout for layers with millions of features

### ISSUE THREAD

**Issue by kbvernon** [R-ArcGIS/arcgislayers#121]
**Describe the bug**
I get a gateway timeout error when trying to open a connection to a service layer with millions of features.

**To Reproduce**
```r
library(arcgislayers)

file.path(
  "https://hydro.nationalmap.gov",
  "arcgis/rest/services",
  "NHDPlus_HR/MapServer/3"
) |> arc_open()
```
gives the error:
```r
Error in `httr2::req_perform()`:
! HTTP 504 Gateway Timeout.
Run `rlang::last_trace()` to see where the error occurred.
```

**Expected behavior**
Return object of class `FeatureLayer`.

**Additional context**
The specific data source is the [USGS National Hydrography Dataset](https://hydro.nationalmap.gov/arcgis/rest/services/NHDPlus_HR/MapServer/) (High Resolution). Layer is (3) NetworkNHDFlowline.

**Comment by JosiahParry** [comment]
``` r
library(arcgislayers)

file.path(
    "https://hydro.nationalmap.gov",
    "arcgis/rest/services",
    "NHDPlus_HR/MapServer/3"
) |> arc_open()
#> <FeatureLayer>
#> Name: NetworkNHDFlowline
#> Geometry Type: esriGeometryPolyline
#> CRS: 3857
#> Capabilities: Data,Map,Query
```

<sup>Created on 2023-12-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
