### ISSUE TITLE
client auth cannot read org shared items

### ISSUE THREAD

**Issue by mmachir** [R-ArcGIS/arcgislayers#13]
`get_layer()` and `get_all_layers()` are failing on a non-public feature service - maybe the token isn't being passed to these functions?

Repro:

- When sharing level is set to Organization (or Owner) for feature layer in ArcGIS Online:

```
library(arcgis)

# set token
Sys.setenv("ARCGIS_TOKEN" = auth_client()[["access_token"]])

# access FeatureServer (shared to Org)
fsurl <- "https://services1.arcgis.com/hLJbHVT9ZrDIzK0I/arcgis/rest/services/Madagascar_points/FeatureServer"
ft_srv <- feature_server(fsurl)
ft_srv

# option to retrieve all layers
fs_list <- get_all_layers(ft_srv)
fs_list$layers
fs_list$tables

# define FeatureLayer
fl <- get_layer(ft_srv, 0)
fl
```
`get_all_layers()` and `get_layer()` both fail and raise this error:
![image](https://user-images.githubusercontent.com/55209116/228963481-78684970-c04e-4351-a90e-1701874c1c43.png)

- If the sharing level is changed from Organization to Public, this same repro works cleanly:
![image](https://user-images.githubusercontent.com/55209116/228964449-a48ec9d8-7517-40cf-82cd-18ba6f7536cf.png)

**Comment by JosiahParry** [comment]
Confirmed that client auth is not expected to be able to publish.
