### ISSUE TITLE
Publish point layers don't render in map layer

### ISSUE THREAD

**Issue by nginer316** [R-ArcGIS/arcgislayers#133]
library(sf)
nc_sf <- read_sf(system.file("shape/nc.shp", package = "sf"))
nc_sf

nc_pts <- st_centroid(nc_sf)
nc_pts

# publish it
pts <- publish_layer(nc_pts, "NC_SIDS_pts")
pts

**Comment by JosiahParry** [comment]
when points are published they dont show up but when added they do hmm
