### ISSUE TITLE
Error reading large datasets

### ISSUE THREAD

**Issue by jsmendozap** [R-ArcGIS/arcgislayers#138]
When I use `arc_read` to open a full dataset, I sometimes get some problems (I don't know if maybe it is related to the dataset size). 

for example: 

This code works
```
url <- 'https://ags.esri.co/arcgis/rest/services/DatosAbiertos/PNN_2005/MapServer/0/'
data <- arc_read(url)
```

However, when I try with another dataset like this:
```
url <- 'https://ags.esri.co/arcgis/rest/services/DatosAbiertos/ELECCIONES_PRESIDENCIALES_2014_MPIO/MapServer/0'
data <- arc_read(url)
```

I get this error:
```
Error in do.call(rbind.data.frame, fts_raw[["attributes"]]) : 
  second argument must be a list
```

**Comment by JosiahParry** [comment]
I think the issue is here: 
https://github.com/R-ArcGIS/arcgislayers/blob/cc4861679e43af88cbb9bee1cc28752261c93d7f/R/arc-select.R#L221-L225

The responses from the feature services _never_ return a 400 code so we won't get an error class. We're not actually catching them. We need to handle errors here. 

<img width="1051" alt="image" src="https://github.com/R-ArcGIS/arcgislayers/assets/13534508/91a89530-f048-4dd4-bb1b-7b4d08c88acd">

**Comment by JosiahParry** [comment]
There are two issues here: 

1. That we're not handling errors appropriately
2. Why does the feature service return a 500 error? This is outside of our control but should know about and figure out how to resolve. Can we increase the timeout?

**Comment by JosiahParry** [comment]
One solutions might be to use smaller batch sizes

**Comment by JosiahParry** [comment]
> One solutions might be to use smaller batch sizes

Confirmed that this is approach taken by the python API. It uses a backoff-style approach and uses smaller and smaller  batch sizes

**Comment by JosiahParry** [comment]
This isn't a _fix_ to the problem, but it is a better solution than what we have presently. Part of the fix is to provide an informative warning. 

``` r
url <- 'https://ags.esri.co/arcgis/rest/services/DatosAbiertos/ELECCIONES_PRESIDENCIALES_2014_MPIO/MapServer/0'
data <- arcgislayers::arc_read(url)
#> Warning in parse_esri_json(httr2::resp_body_string(x)): Status code: 500
#> Error: Error performing query operation
data
#> data frame with 0 columns and 0 rows
```

<sup>Created on 2024-02-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
