### ISSUE TITLE
Managing multiple organizations

### ISSUE THREAD

**Issue by mmachir** [R-ArcGIS/arcgislayers#15]
This is a general question but I just want to put it out there for consideration:

Does this R api currently support users who may work with multiple different "organizations" (i.e., AGOL orgs and/or Enterprise portals)? This isn't as uncommon as one might think for our users, in my experience. Examples:

- User manages separate QA, Dev, and Prod Enterprises for their organization
- User interacts with a public-facing ArcGIS Online org plus an internal Enterprise
- User does some work in different but related ArcGIS Online orgs (one for their government agency and a separate interagency ArcGIS Online org for sharing data between related agencies)
- etc.

I don't by any means think this should be the default set-up/assumption about users of the R api, but I think it would be good to have some patterns where users can work in multiple or different orgs/portals if they needed to.

In the python api, a user can set up multiple GIS() constructors to represent the different orgs/portals, so for example:
```
import os
from arcgis import GIS
my_agol = GIS("https://www.arcgis.com",username="mbass_ANGP",password=os.environ['AGOL_PASSWORD'])
my_portal = GIS("https://gpportal.esri.com/portal",username="admin",password=os.environ['GPPORTAL_PASSWORD'])
```
I don't think the R API has to match up with this and it seems like the R API potentially already supports this, like so?

```
agol_token <- auth_client(client="agol-client-info", secret = "agol-secret")
portal_token <- auth_client(client="portal-client-info", secret = "portal-secret")

agol_fl <- feature_layer("agol-fl-url", token = agol_token)
portal_fl <- feature_layer("portal-fl-url", token = portal_token)
```

Just something for consideration as development and documentation continue!

**Comment by JosiahParry** [comment]
Related: https://github.com/R-ArcGIS/arcgislayers/discussions/132
