### ISSUE TITLE
Support RasterLayer service type in get_layer and variants

### ISSUE THREAD

**Issue by thuja** [R-ArcGIS/arcgislayers#158]
**Is your feature request related to a problem? Please describe.**
I wanted to load rasters that are located in this MapServer service (https://gis-dev.dnr.wa.gov/site2/rest/services/Public_Forest_Mgmt/WADNR_PUBLIC_RS_FRIS_Rasters/MapServer) to programmatically extract data. There are 44 layers and having access from R will greatly speed processing.

**Describe the solution you'd like**
Be able to load RasterLayers from a MapServer service.

**Describe alternatives you've considered**
Downloading individual files manually then processing.

**Additional context**

**Comment by JosiahParry** [comment]
@thuja, I've checked with my team and they've confirmed that MapServer Raster Layers are essentially just pictures without any associated data. You would need to access the underlying data from an ImageServer. Do you know if the original data is available as an ImageServer?
