### ISSUE TITLE
Basic example does not appear to be working

### ISSUE THREAD

**Issue by mhweber** [R-ArcGIS/arcgislayers#164]
The basic functionality of running a field based query on the ReadMe page does not appear to be working.

`library(arcgis)
furl <- "https://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/USA_Counties_Generalized_Boundaries/FeatureServer/0"
county_fl <- arc_open(furl)
arc_select(county_fl)`

Generates this error:
`Error in cli::cli_progress_update(..., id = id) : 
Cannot find progress bar `cli-128996-172`
Error in cli::cli_progress_update(..., id = id) : 
Cannot find progress bar `cli-128996-172``

**Comment by mhweber** [comment]
@JosiahParry - restarting worked - thanks, glad it was that simple! Looks like a really useful package, excited to start using.

**Comment by JosiahParry** [comment]
Brilliant! I think sometimes the cli package loses track of the progress bar which is what caused that. Sorry!
