### ISSUE TITLE
Clarify when authorization is or is not required in the documentation

### ISSUE THREAD

**Issue by hrecht** [R-ArcGIS/arcgislayers#172]
**Is your feature request related to a problem? Please describe.**
The README currently states at the top, "arcgislayers requires {arcgisutils} for authorization."
As a new user who only reads data from ArcGIS, not writes, this was confusing. I assumed I'd need a user account and authorization for any use of the package, including reading public datasets from the REST API. 

**Describe the solution you'd like**
I would take this authorization sentence out of the top of the installation section entirely. From my test using the reprex at https://github.com/hrecht/cherry-blossoms-analysis/issues/1 I did not need to do anything related to authorization to install the package or run `arc_open()` and `arc_select()`. The current placement makes it appear as though you need a user account and need to authenticate before doing anything with the package at all.

The authentication section at the bottom could clearly state that authentication is NOT required for functions x, y, z - whichever those are.

**Additional context**
I'd be happy to submit a PR with a suggested fix but I know from experience that it can be a lot simpler to just handle it yourself! Whichever is easier.

**Comment by JosiahParry** [comment]
Valid! @mmachir any chance you have the bandwidth to assist with this?
