### ISSUE TITLE
publish_layer() fails with mapply error

### ISSUE THREAD

**Issue by mmachir** [R-ArcGIS/arcgislayers#184]
**Describe the bug**
Publishing a hosted feature layer using `publish_layer()` is failing currently.

**To Reproduce**
``` r
library(arcgis)
#> Attaching core arcgis packages:
#> → arcgisutils v0.2.0.9000
#> → arcgislayers v0.2.0
set_arc_token(auth_user())
nc <- sf::read_sf(system.file("shape/nc.shp", package = "sf"))
res <- publish_layer(nc, "NorthCarolinaSIDS_test1")
#> Warning in mapply(function(.x, .y) c(list(attributes = c(.y)), geometry =
#> list(.x)), : longer argument not a multiple of length of shorter
```

<sup>Created on 2024-04-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Expected behavior**
Publishing should succeed with the valid input data (nc.shp).

**Additional context**
N/A

**Comment by JosiahParry** [comment]
This work is being done in https://github.com/JosiahParry/serde_esri/tree/geom

It's almostttt done. I'll need to figure out how to get this into arcgisutils though. I'm torn between two options:

- put Rust code inside of arcgisutils and remove C code
- create another small utility package for json much like arcpbf but here it could be esrijson or something and importing it into arcgisutils

@elipousson this will affect you. Do you have a stance?

**Comment by JosiahParry** [comment]
The work being done in serde_esri can also be used to create arrays of features, individual geometries, as well as parse esri json more cleanly. 

I think it might be worth the effort to migrate it _all_ to using serde_esri. Most of the scaffolding is there. 

What is not:

- creating feature sets with `M` or `ZM`
- parsing json similarly to `arcpbf::resps_body_pbf()`

This also means that all functions will create the json string directly and _not_ create a list object. So this means all `as_geometry()`, `as_features()` and `as_featureset()` will have to be deprecated.

**Comment by JosiahParry** [comment]
This is probably also the same time to fix `validate_crs()` I think. Hm.

**Comment by elipousson** [comment]
I haven't built anything on top of the lower-level functions directly so, unless there are some possible consequences that I'm not thinking of, I'm somewhat agnostic on the solution.

It all sounds promising though! Happy to help test when it is ready.

**Comment by JosiahParry** [comment]
This is drafted in https://github.com/R-ArcGIS/arcgisutils/pull/48.
