### ISSUE TITLE
arc_raster() sample code error

### ISSUE THREAD

**Issue by mmachir** [R-ArcGIS/arcgislayers#190]
**Describe the bug**
Running the sample code from the [arc_raster() reference](https://r.esri.com/arcgislayers/reference/arc_raster.html) produces an error. Not sure if it has to do with the underlying service rather than the package, but if so, perhaps the example can be updated.

**To Reproduce**
``` r
library(arcgis)
#> Attaching core arcgis packages:
#> → arcgisutils v0.3.0
#> → arcgislayers v0.2.0

img_url <- "https://landsat2.arcgis.com/arcgis/rest/services/Landsat/MS/ImageServer"

landsat <- arc_open(img_url)

arc_raster(
  landsat,
  xmin = -71,
  ymin = 43,
  xmax = -67,
  ymax = 47.5,
  bbox_crs = 4326,
  width = 100,
  height = 100
)
#> Warning:
#> C:\Users\XXXXXX\AppData\Local\Temp\1\RtmpK8SNxg\file79141a585e28.tiff:
#> _TIFFVSetField:C:\Users\XXXXXX\AppData\Local\Temp\1\RtmpK8SNxg\file79141a585e28.tiff:
#> Bad value 2573 for "ExtraSamples" tag (GDAL error 1)
#> Error: [rast] cannot open this file as a SpatRaster: C:\Users\XXXXXX\AppData\Local\Temp\1\RtmpK8SNxg\file79141a585e28.tiff
```

<sup>Created on 2024-06-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Expected behavior**
Expect the code to successfully export the image as a SpatRaster or throw a meaningful error.

**Additional context**
N/A

**Comment by elipousson** [comment]
I wonder if this is a passing issue with the service – I am running the development versions of everything but I was not able to reproduce the error.

**Comment by JosiahParry** [comment]
I think this might be an issue with conflicting GDAL installations?

**Comment by mmachir** [comment]
Thank you both @elipousson @JosiahParry! I do think this is almost certainly an issue with GDAL installations- I have all kinds of python envs and such on the machines that this repros on. I'll close this but if I'm able to figure out what's going on here, I'll come back and add some details in case anyone else faces a similar issue.

**Comment by mmachir** [comment]
Oops forgot to actually close it.
