### ISSUE TITLE
Helper for making alias column names

### ISSUE THREAD

**Issue by JosiahParry** [R-ArcGIS/arcgislayers#60]
When running arc_select() or collect() the returned data frame does not use the alias of the field. The alias is often more human readable than the field name. It may be preferable to return the column names as the alias

**Comment by elipousson** [comment]
Not sure if there is a way to do this without picking up an additional dependency but I think aliases are actually more equivalent to variable labels as implemented by the `{labelled}` package and they are often not well suited to using as column names directly: https://larmarange.github.io/labelled/articles/intro_labelled.html#variable-labels

One possibility could be to add a `.name_repair` argument and a helper function that, if used for `.name_repair`, could replace the column names with the alias values. Likely the same helper could be adapted to make variable labels for anyone using `arcgislayers::arc_select()` in combination with `labelled::var_labels()`.

I added a `.name_repair` argument to `esri2sf::esri2sf()` so I could use it in combination with the handy `janitor::make_clean_names()` function. For `{esri2sf}`, I'm just passing the argument to `tibble::as_tibble()` but you could use the underlying `vctrs::vec_as_names()` function directly.

**Comment by JosiahParry** [comment]
You're right, re labels. I was thinking of the labels behavior of haven. I wonder if there is a good way out of this without over engineering `arc_select()`. Perhaps a utility function like `field_aliases()` can be used in combination with rename. This does feel contrived though..

```r
library(dplyr)

library(arcgis)
#> Attaching core arcgis packages:
#>   - {arcgisutils} v0.1.0
#>   - {arcgislayers} v0.1.0

# define the feature layer url
furl <- "https://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/USA_Counties_Generalized_Boundaries/FeatureServer/0"

county_fl <- arc_open(furl)

# helper function
field_aliases <- function(x) {
  fields <- list_fields(x)
  setNames(fields[["name"]], fields[["alias"]])
}

county_fl |> 
  collect() |> 
  rename(!!!field_aliases(county_fl))
#> Simple feature collection with 3142 features and 12 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -178.2176 ymin: 18.92179 xmax: -66.96927 ymax: 71.40624
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>    OBJECTID            Name State Name State FIPS  FIPS Area in square miles
#> 1         1  Autauga County    Alabama         01 01001               604.37
#> 2         2  Baldwin County    Alabama         01 01003              1633.14
#> 3         3  Barbour County    Alabama         01 01005               904.52
#> 4         4     Bibb County    Alabama         01 01007               626.17
#> 5         5   Blount County    Alabama         01 01009               650.63
#> 6         6  Bullock County    Alabama         01 01011               625.14
#> 7         7   Butler County    Alabama         01 01013               777.88
#> 8         8  Calhoun County    Alabama         01 01015               612.27
#> 9         9 Chambers County    Alabama         01 01017               603.11
#> 10       10 Cherokee County    Alabama         01 01019               599.98
#>    2020 Total Population People per square mile State Abbreviation County FIPS
#> 1                  58805                   97.3                 AL         001
#> 2                 231767                  141.9                 AL         003
#> 3                  25223                   27.9                 AL         005
#> 4                  22293                   35.6                 AL         007
#> 5                  59134                   90.9                 AL         009
#> 6                  10357                   16.6                 AL         011
#> 7                  19051                   24.5                 AL         013
#> 8                 116441                  190.2                 AL         015
#> 9                  34772                   57.7                 AL         017
#> 10                 24971                   41.6                 AL         019
#>    Shape__Area Shape__Length                       geometry
#> 1    0.1489034      1.884137 MULTIPOLYGON (((-86.82067 3...
#> 2    0.4044891      3.678276 MULTIPOLYGON (((-87.97309 3...
#> 3    0.2224307      2.218514 MULTIPOLYGON (((-85.74337 3...
#> 4    0.1577359      1.852453 MULTIPOLYGON (((-87.41986 3...
#> 5    0.1675296      2.067456 MULTIPOLYGON (((-86.96799 3...
#> 6    0.1557273      2.006250 MULTIPOLYGON (((-85.4114 32...
#> 7    0.1927305      1.769462 MULTIPOLYGON (((-86.44912 3...
#> 8    0.1523369      2.149825 MULTIPOLYGON (((-85.79353 3...
#> 9    0.1531136      1.637226 MULTIPOLYGON (((-85.58963 3...
#> 10   0.1527217      1.794142 MULTIPOLYGON (((-85.41657 3...
```

**Comment by elipousson** [comment]
I really like this approach. I did something similar in my getdata package: https://github.com/elipousson/getdata/blob/65668b09a1c1e564b8f6dfb18dec88cd2aa7fed9/R/format_data.R#L137-L183

`fields_alias()` should take an optional fields column (same as `arcgislayers::arc_select()`) so you can subset the alias values and make sure you can use the aliases to rename a `sf` object that has the same subset of the original columns.

**Comment by JosiahParry** [comment]
Reviewing this, I think that there should be a utility function that would be in the same bucket as [`refresh_layers`](https://r.esri.com/arcgislayers/reference/refresh_layer.html) that most people wont have a need for. 

Renaming columns is out of the scope of these packages but providing handy utilities might not be.

**Comment by JosiahParry** [comment]
I'm going to close this for now as I think its out of the scope of the main functionality. If it comes back up we can write a FAQ / short workflow article on this.
