### ISSUE TITLE
Add support for `sf` and `bbox` class objects to `filter_geom` argument in `arcgislayers::arc_select()`

### ISSUE THREAD

**Issue by elipousson** [R-ArcGIS/arcgislayers#61]
I'd love to see `arcgislayers::arc_select()` updated to add support for `bbox` class and `sf` class objects as a spatial filter. This is a basic example of a wrapper that would do the same thing – happy to take a look at the function and open a pull request to add this feature if it is welcome. 

```
arc_select_filter_geom_ext <- function(..., filter_geom = NULL) {
  
  if (inherits(filter_geom, "bbox")) {
    filter_geom <- sf::st_as_sfc(filter_geom)
  } else if (inherits(filter_geom, "sf")) {
    filter_geom <- sf::st_geometry(filter_geom)
  }
  
  arcgislayers::arc_select(..., filter_geom = filter_geom)
}
```

**Comment by JosiahParry** [comment]
I agree using a bbox would be quite useful to dispatch on. I do think using an `sf` object, though is a bit of a misuse of the object itself. There should be clarity that we are filtering based on a single geometry and not based on any attributes. For that reason I think limiting it to strictly geometric objects is important. A `cli::cli_abort()` could be raised when an `sf` object is provided with the suggestion to use `sf::st_geometry()` instead.

**Comment by JosiahParry** [comment]
Overall, the error's and type handling here could be vastly improved: 
https://github.com/R-ArcGIS/arcgislayers/blob/3a1254ac1c8d156e22419c964d7eb86ae9920daa/R/arc-select.R#L26

**Comment by elipousson** [comment]
I can understand the preference to avoid support for `{sf}` inputs. I could make the case in favor but I don't feel that strongly about it.

I have two helper functions in `{esri2sf}` that would be easy to adapt into better input checks for `filter_geom`:

- `sf2geometry()`: https://github.com/elipousson/esri2sf/blob/master/R/esri2sf.R#L472-L508
- `sf2geometryType()`: https://github.com/elipousson/esri2sf/blob/master/R/esri2sf.R#L436-L469

Happy to start working something up and share a pull request next week sometime if it is helpful.
