### ISSUE TITLE
Bug handling of spatial filter in add update and delete

### ISSUE THREAD

**Issue by JosiahParry** [R-ArcGIS/arcgislayers#69]
https://github.com/R-ArcGIS/arcgislayers/blob/ea13571ff95b88398e3ff08313c9ae733de3184a/R/arc-add-update-delete.R#L265C10-L265C10

CC @elipousson

**Comment by JosiahParry** [comment]
This line uses the CRS of `x` and ignores the spatial reference of `filter_geom`. It should prefer CRS of filter_geom and if is sfg or is.na() we use that of `x`

**Comment by JosiahParry** [comment]
Closed by #80

**Comment by elipousson** [comment]
Should taking the CRS from filter_geom vs. x be controlled by an option? I get the logic but also kind of weird for the output CRS to be determined by the spatial filter object. Is there still an option to set an output CRS that could override both filter_geom and x?

**Comment by JosiahParry** [comment]
It doesn't. The spatial filter object can have a different CRS than the feature layer. The CRS of  prepare_spatial_filter() is used to to determine what CRS the spatial filter object is in--not the output.

**Comment by elipousson** [comment]
Aha. Thanks for clarifying. Probably should have waited until I was looking at the code again before asking!
